### PR TITLE
Adds ability to predictably map known variables

### PR DESCRIPTION
**Pull request by geometricpanda**
Allows consumers to pass in an object to predictably shorten css variables

### CODE REVIEW

**Comment by navanshu** [comment]
@geometricpanda 
Interesting work, let me run some test on it and optimize it a bit.
Then I will push it to npm

**Review by navanshu — APPROVED** [review]
Great work and thanks for addition.

**Comment by navanshu** [comment]
Sorry I had to reverse this it broke some code.

**Comment by geometricpanda** [comment]
> Sorry I had to reverse this it broke some code.

No worries, can you share what it broke and i'll see if i can fix it?

**Comment by navanshu** [comment]
I am planning to take the parameters like an object in a well defined manner. Like other libraries does but that will be only after a major release which is going to have even more features.
For now the second parameter will be an ``` [String, String][]``` not an object the one you plan to add, that has these values. This array will be passed in the existing map. So it will not increase the burden of more code.

Plus with your changes we need to figure out two things.
Suppose the map is saying that --height should be mapped to --h
But the skip function is saying to skip --height.
Which of the following case will win and why.
This needs to follow some convention.

**Comment by geometricpanda** [comment]
If you want any help, DM me on twitter and i'd happily collab

**Comment by navanshu** [comment]
I am just busy with the ongoing work, just trying to get some rest. 
Lets talk soon.

**Pull request merged**
